### ISSUE TITLE
Missing Vcc connection to ESP-01 pin CHIP-EN

### ISSUE THREAD

**Issue by F5HNK** [f5soh/balise_esp32#1]
I suggest this layout in order to activate the ESP82266 chip when using the ESP-01 as standalone.
![balise_esp32](https://user-images.githubusercontent.com/66332988/84069133-914ce100-a9b9-11ea-9279-aad0f8be49d0.png)

**Comment by f5soh** [comment]
Thanks, missed this pin.
Updated
