### ISSUE TITLE
class droneIDFR

### ISSUE THREAD

**Issue by adri94** [f5soh/balise_esp32#2]
Bonjour,

Je ne comprends pas pourquoi j'ai cette erreur. Pouvez-vous m'aider ? 

Merci,

balise_esp32:158:28: error: 'class droneIDFR' has no member named 'set_home_lat_lon'
                 drone_idfr.set_home_lat_lon(gps.location.lat(), gps.location.lng());
                            ^
balise_esp32:163:24: error: 'class droneIDFR' has no member named 'set_lat_lon'
             drone_idfr.set_lat_lon(gps.location.lat(), gps.location.lng());
                        ^
balise_esp32:164:24: error: 'class droneIDFR' has no member named 'set_altitude'
             drone_idfr.set_altitude(gps.altitude.meters());
                        ^
balise_esp32:167:24: error: 'class droneIDFR' has no member named 'set_heigth'
             drone_idfr.set_heigth(gps.altitude.meters() - home_alt);
                        ^
exit status 1
'class droneIDFR' has no member named 'set_home_lat_lon'

**Comment by f5soh** [comment]
Il faut récupérer **tous** les fichiers de ce repo, la librairie droneID_fr est modifiée et les appels sont différents.

**Comment by f5soh** [comment]
Il faut récupérer **tous** les fichiers de ce repo, la librairie droneID_fr est modifiée et les appels sont différents.
